name: hello-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "Hello GitHub Actions!"
