name: secrets
on: push
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print secret length
        shell: python
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          import os
          print(len(os.getenv("SECRET")))
